import lifts from '../lifts/index.js';

lifts('alpedhuez', 'html', {
  'Pic Blanc': 'scheduled',
  Herpie: 'closed',
  'Dmc Grandes Rousses': 'scheduled',
  'Lac Blanc': 'scheduled',
  'Lièvre Blanc': 'closed',
  'Rif Nel Express': 'open',
  'Marmottes 2': 'closed',
  'Marmottes 3': 'closed',
  'Marmottes 1': 'closed',
  Romains: 'closed',
  Chalvet: 'closed',
  'Tapis Bergers': 'open',
  'Tapis Moutons': 'closed',
  'Tapis Rif Nel 1': 'closed',
  'Tapis Rif Nel 2': 'closed',
  Jeux: 'closed',
  Signal: 'scheduled',
  'Grande Sure': 'closed',
  Babars: 'closed',
  'Ecole 1': 'closed',
  'Ecole 2': 'closed',
  Poutran: 'closed',
  Sagnes: 'closed',
  Stade: 'closed',
  'Tapis Grenouilles': 'closed',
  'Alpe Express': 'closed',
  'Huez Express': 'closed',
  Télécentre: 'closed',
  Sures: 'scheduled',
  Alpauris: 'closed',
  'Auris Express': 'closed',
  Fontfroide: 'closed',
  Louvets: 'closed',
  Lombards: 'closed',
  Maronne: 'closed',
  'Forêt': 'closed',
  'Piégut': 'closed',
  'Tapis Bambin': 'closed',
  'Tapis Bauchets': 'closed',
  Villarais: 'scheduled',
  Cloudit: 'closed',
  Langaret: 'closed',
  'Petit Prince': 'closed',
  Tortue: 'closed',
  'Ascenseur Villard': 'closed',
  'Tapis Escargots': 'closed'
});
