import lifts from '../lifts/index.js';

lifts('are', 'html', {
  // Åre By
  'VM8:an': 'open',
  Stjärnliften: 'open',
  'VM6:an': 'open',
  Hummelliften: 'open',
  Fjällgårdsexpressen: 'open',
  'Ullådalsliften 1': 'closed',
  'Ullådalsliften 2': 'closed',
  'Rödkulleliften 1': 'closed',
  'Rödkulleliften 2': 'closed',
  Bräckeliften: 'open',
  Tottliften: 'closed',
  Rödhakeliften: 'open',
  'Ripanliften 1': 'closed',
  'Ripanliften 2': 'closed',
  Bergbanan: 'open',
  'Rullband - Rödkullen': 'closed',
  // Åre Högzon
  Kabinbanan: 'closed',
  Gondolen: 'closed',
  Stendalsliften: 'closed',
  'Nedre Tväråvalvsliften 2': 'closed',
  'Nedre Tväråvalvsliften 1': 'closed',
  'Övre Tväråvalvsliften': 'closed',
  // Åre Björnen
  Sadelexpressen: 'closed',
  Högåsliften: 'closed',
  Hermelinenliften: 'closed',
  Björnenliften: 'closed',
  Järvenliften: 'closed',
  Vikliften: 'closed',
  Getvalsliften: 'closed',
  Lokattliften: 'closed',
  Vargenliften: 'closed',
  Mårdenliften: 'closed',
  Nalleliften: 'closed',
  'Copperhill liften': 'closed',
  'Vesslan Rullband - Björnen': 'closed',
  // Duved
  'Duveds Linbana': 'closed',
  Tegeliften: 'closed',
  Hamreliften: 'closed',
  Leråliften: 'closed',
  Englandsliften: 'closed',
  Gunnilliften: 'closed',
  Fjällvallsliften: 'closed',
  Byliften: 'closed',
  Torpliften: 'closed',
  'Mini Tege': 'closed',
  'DR1 Rullband - Duved': 'closed',
  'DR2 Rullband - Tegefjäll': 'closed'
});
